### ISSUE TITLE
Files missing in pypi 0.4.4 tarball

### ISSUE THREAD

**Issue by afaerber** [xZise/flake8-future-import#14]
The `LICENSE` file available in the Git repository is missing in the 0.4.4 tarball currently available on https://pypi.python.org/pypi/flake8-future-import/0.4.4 despite being older than that release. Please have it added to future tarballs.

Similarly, `test_flake8_future_import.py` is missing in the pypi tarball, so that `setup.py test` fails.

Found during packaging review for openSUSE.

**Comment by xZise** [comment]
I've added both files to the tarball, so this should be resolved.

**Comment by afaerber** [comment]
Thanks!
