### ISSUE TITLE
Multiple-letter violation codes are not displayed by Vim Syntastic syntax checker

### ISSUE THREAD

**Issue by myii** [xZise/flake8-future-import#15]
**This is not a bug with your plugin** but I'm raising this here for your awareness, since you use multiple-letter violation code(s).

I've filed an issue with `vim-syntastic`: https://github.com/vim-syntastic/syntastic/issues/2163.

The resolution of that bug may be of interest to you.  If not, please disregard this report, with my apologies.

Note, this may be related to issue #5.

**Comment by myii** [comment]
The Syntastic issue has been resolved so I'll close this issue, too.

It required a bit of extra work to accommodate `FIxx` but we got there in the end.

**Comment by xZise** [comment]
This is good to hear. As mentioned in #5 there isn't really a sensible single letter code available, as far as I can see.
