### ISSUE TITLE
pip 10 test failure

### ISSUE THREAD

**Issue by FRidh** [xZise/flake8-future-import#17]
Testing fails with pip 10 because it depends on pip internals:
```
======================================================================
ERROR: setUpClass (test_flake8_future_import.Flake8TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/test_flake8_future_import.py", line 245, in setUpClass
    for dist in pip.utils.get_installed_distributions():
AttributeError: 'module' object has no attribute 'utils'

----------------------------------------------------------------------
```
In pip 10 functions like these are internal, that is, `pip._internals.get_installed_distributions`.

**Comment by xZise** [comment]
Thanks for mentioning it here. I've looked into it and it seems that it's not intended for external usage (see pypa/pip#5154) so I'm currently looking into a canonical way without resorting to an undocumented API.

**Comment by xZise** [comment]
I've implemented a fix and it doesn't fail on Travis anymore, although it manually needs to install `flake8` before running the tests. Not sure what the more elegant solution would be, apart from using pip's function which doesn't really look elegant considering it isn't documented.
