### ISSUE TITLE
test_annotations broken with Python 3.8.6

### ISSUE THREAD

**Issue by mweinelt** [xZise/flake8-future-import#24]
The tests broke when upgrading from 3.8.5 to 3.8.6. This is due to the following change:

> bpo-41314: Changed the release when from __future__ import annotations becomes the default from 4.0 to 3.10 (following a change in PEP 563).

```
======================================================================
FAIL: test_annotations (test_flake8_future_import.TestFeatures)
Verify the feature versions.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/test_flake8_future_import.py", line 314, in test
    self.assertEqual(my_feat.mandatory, py_feat.mandatory[:3])
AssertionError: Tuples differ: (4, 0, 0) != (3, 10, 0)

First differing element 0:
4
3

- (4, 0, 0)
?  ^

+ (3, 10, 0)
?  ^  +
```

**Comment by xZise** [comment]
Hi, this took a while, but for now I'm skipping this test with c595b8f2. It was changing quite a bit (from 4.0.0 to 3.10.0 to 3.11.0 and now `None`) and so my idea would be to set the mandatory version to `None` too.
