### ISSUE TITLE
Use flake8 error code format

### ISSUE THREAD

**Issue by vcabbage** [xZise/flake8-future-import#5]
flake8 defines warning and error codes as "an upper case ASCII letter followed by three digits" (http://flake8.readthedocs.org/en/latest/warnings.html). FI## doesn't fit this format.

I ran into the issue with Jenkins' Violations plugin which uses a strict regex which doesn't match the FI## pattern (https://github.com/jenkinsci/violations-plugin/blob/cab7103b/src/main/java/hudson/plugins/violations/types/pep8/Pep8Parser.java#L41).

Would you be open to changing the error code format? Possibly using an opt-in flag to avoid to not break existing configurations.

**Comment by xZise** [comment]
In principle yes, but to be honest there are only so much letters (aka 26) and so it's problematic to use another letter. `F` is already used by pep8/flake8 itself and `I` is used by the [*flake8-import-order*](https://pypi.python.org/pypi/flake8-import-order/0.7).

But maybe it's possible to share the same letter, especially as my plugin is similar to *flake8-import-order*. And an opt-in flag would certainly be possible but the question is what other prefix. Making it completely free would probably cause to much confusion, but in case I'm going to change it, it is probably sensible. Although I don't consider it finished and so users should expect that the format changes (maybe with a grace period where it's possible to opt-in into the new first, then opt-out into the old).

**Comment by lorengordon** [comment]
I suspect this might also be the reason the flake8-linter for Atom does not display the violations raised by this plugin. Following their code is difficult for me, but I think perhaps [this regex](https://github.com/AtomLinter/linter-flake8/blob/master/lib/main.js#L10) is the issue...

**Comment by labrys** [comment]
@xZise It is possible to share codes with other projects.  For example `flake8-commas` and `flake8-comprehensions` both use the `Cxxx` namespace which is already used by flake8 for cyclomatic complexity.  The issue is to make sure to not stomp on the same error code ranges.  As your project won't ever likely have a large number of error codes, I don't see this as an issue.  I would probably contact the existing project (e.g. flake8-import-order) as a courtesy to avoid namespace collisions.

**Comment by xZise** [comment]
I actually [raised this issue](https://github.com/PyCQA/flake8-import-order/issues/68#issuecomment-229363122) with the other plugin and you probably won't like their response.

**Comment by xZise** [comment]
Hi, as noted in the [documentation of Flake8](https://flake8.pycqa.org/en/5.0.4/plugin-development/registering-plugins.html) itself, the code can be build from up to three letters. As such I'd prefer to stay with the current format for now.
